import org.jetbrains.kotlin.gradle.tasks.KotlinCompile

plugins {
    alias libs.plugins.org.jetbrains.kotlin.jvm apply false
    alias libs.plugins.android.application
    alias libs.plugins.android.library apply false
    alias libs.plugins.kotlin
    alias libs.plugins.google.protobuf
    alias libs.plugins.ksp
    alias libs.plugins.bliss.spotless
    alias libs.plugins.bliss.githooks
    alias libs.plugins.kotlin.serialization
}

afterEvaluate {
    tasks.prepareKotlinBuildScriptModel.dependsOn(tasks.copyGitHooks, tasks.installGitHooks)
}

allprojects {
    var FRAMEWORK_PREBUILTS_DIR = "$rootDir/libs/"

    ext.addFrameworkJar = { String name ->
        def frameworkJar = new File(FRAMEWORK_PREBUILTS_DIR, name)
        if (!frameworkJar.exists()) {
            throw new IllegalArgumentException("Framework jar path ${frameworkJar.path} doesn't exist")
        }

        gradle.projectsEvaluated {
            tasks.withType(JavaCompile).configureEach {
                classpath = files(frameworkJar, classpath)
            }
            tasks.withType(KotlinCompile).configureEach {
                libraries.from(files(frameworkJar))
            }
        }

        dependencies {
            compileOnly files(frameworkJar)
        }

        dependencies {
            compileOnly fileTree(dir: FRAMEWORK_PREBUILTS_DIR, include: 'Launcher3QuickStepLib')
        }
    }
}

var appVersionCode = 3010031
var appVersion = "3.1.4"

def versionPropsFile = file('local.properties')
Properties versionProps = new Properties()

if (versionPropsFile.exists()) {
    versionProps.load(new FileInputStream(versionPropsFile))
}

if (!versionProps.containsKey('VERSION_CODE')) {
    versionProps['VERSION_CODE'] = appVersionCode.toString()
    versionProps.store(versionPropsFile.newWriter(), null)
}

def getVersionCode = { ->
    if (versionPropsFile.canRead()) {
        versionProps.load(new FileInputStream(versionPropsFile))
        def versionCode = versionProps['VERSION_CODE'].toInteger()
        versionProps['VERSION_CODE'] = (versionCode.toInteger() + 1).toString()
        versionProps.store(versionPropsFile.newWriter(), null)
        return versionCode
    }
}

android {
    namespace "com.android.launcher3"
    compileSdk 36

    defaultConfig {

        minSdkVersion 35
        targetSdkVersion 35
        versionCode getVersionCode()
        versionName appVersion

        buildConfigField "boolean", "IS_STUDIO_BUILD", "false"
        buildConfigField "boolean", "WIDGET_ON_FIRST_SCREEN", "false"
        buildConfigField "boolean", "IS_DEBUG_DEVICE", "false"
        buildConfigField "boolean", "WIDGETS_ENABLED", "true"
        buildConfigField "boolean", "NOTIFICATION_DOTS_ENABLED", "true"
    }

    signingConfigs {
        platformConfig {
            storeFile file("$rootDir/keystore/platform.jks")
            storePassword 'platform'
            keyAlias 'platform'
            keyPassword 'platform'
        }
    }

    // Cleanup task to delete the filteredRes directory once before all filtering
    tasks.register("cleanFilteredRes", Delete) {
        delete "$rootDir/build/filteredRes"
    }

    applicationVariants.configureEach { variant ->
        // APK renaming
        variant.outputs.configureEach { output ->
            output.outputFileName = "BlissLauncher-a15-${variant.buildType.name}.apk"
        }

        def variantNameCap = variant.name.capitalize()
        def taskName = "filterAndroidPrvFor${variantNameCap}"
        def filteredResDir = "$rootDir/build/filteredRes/${variant.name}"

        // Collect real res folders
        def resDirs = variant.sourceSets*.res.srcDirs.flatten().unique().findAll { it.exists() }

        // Python script task
        tasks.register(taskName, Exec) {
            description = "Filter androidprv: from XMLs for ${variant.name}"
            group = "preprocessing"
            dependsOn("cleanFilteredRes") // ensure filteredRes dir is cleaned first
            commandLine = ["python3", "filter_androidprv.py", filteredResDir] + resDirs*.absolutePath
        }

        // Update resource folders for this variant
        variant.sourceSets.each { sourceSet ->
            def updatedDirs = [file(filteredResDir)] + sourceSet.res.srcDirs
            sourceSet.res.setSrcDirs(updatedDirs)
        }

        // Ensure script runs before resources are merged
        tasks.named("merge${variantNameCap}Resources").configure {
            dependsOn(taskName)
        }
    }

    buildTypes {
        debug {
            minifyEnabled false
            signingConfig signingConfigs.platformConfig
        }

        release {
            minifyEnabled true
            shrinkResources true
            proguardFiles(getDefaultProguardFile("proguard-android.txt"), "proguard-rules.pro")
            signingConfig = signingConfigs.platformConfig
        }
    }

    flavorDimensions.addAll("app", "recents")

    productFlavors {
        bliss {
            dimension "app"
            applicationId 'foundation.e.blisslauncher'
            isDefault true
        }

        withQuickstep {
            dimension "recents"
        }

        configureEach {
            buildConfigField("String", "SENTRY_DSN", "\"${System.getenv("SENTRY_DSN")}\"")
        }
    }

    sourceSets {
        main {
            res.srcDirs = ['res', 'libs_systemui/animationlib/res', 'libs_systemui/iconloaderlib/res']
            java.srcDirs = ['src', 'compose/core', 'compose/disabled', 'tests/multivalentTests/shared']
            manifest.srcFile 'AndroidManifest-common.xml'
            proto.srcDirs = ['protos/', 'quickstep/protos_overrides/']
        }

        bliss {
            java.srcDirs = ['bliss/src', 'quickstep/dagger', 'quickstep/compose/core','quickstep/compose/disabled', 'quickstep/src_protolog']
            res.srcDirs = ['bliss/res', 'studio_res']
            manifest.srcFile "bliss/AndroidManifest.xml"
            assets.srcDirs 'bliss/assets'
        }

        blissWithQuickstep {
            manifest.srcFile "quickstep/AndroidManifest-launcher.xml"
        }

        withQuickstep {
            res.srcDirs = ['quickstep/res', 'quickstep/recents_ui_overrides/res']
            java.srcDirs = ['quickstep/src', 'quickstep/recents_ui_overrides/src']
            manifest.srcFile "quickstep/AndroidManifest.xml"
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    buildFeatures {
        buildConfig true
    }

    tasks.withType(KotlinCompile).configureEach {
        kotlinOptions {
            freeCompilerArgs += ["-Xjvm-default=all"]
        }
    }

    lint {
        abortOnError true
        checkReleaseBuilds false
        disable 'LogNotTimber'
    }


    addFrameworkJar('framework.jar')

    preBuild.dependsOn 'makeReleaseJar'
}

tasks.register("makeReleaseJar", Jar) {
    archiveFileName.set("Launcher3QuickStepLib.jar")
    destinationDirectory.set(file("libs"))

    def outputFile = file("libs/Launcher3QuickStepLib.jar")
    onlyIf {
        if (outputFile.exists()) {
            println("Launcher3QuickStepLib.jar already exists. Skipping task.")
            return false  // Skip task execution
        }
        return true
    }

    from(zipTree("libs/classes.jar")) {
        include("**/*.class")
        exclude(
                "android/support/v4/**", "androidx/**", "com/airbnb/**",
                "com/android/launcher3/**", "com/android/quickstep/**",
                "com/google/**", "kotlin/**", "kotlinx/**",
                "META-INF/**", "okio/**", "org/**", "_COROUTINE/**",
                "dagger/**", "javax/**", "com/android/systemui/contextualeducation/**",
                "com/android/app/animation/**", "okhttp3/**", "io/sentry/**", "io/reactivex/rxjava3/**",
                "retrofit2/**", "timber/**", "foundation/**"
        )
    }
}

dependencies {
    api libs.airbnb.lottie

    implementation libs.androidx.core
    implementation libs.androidx.appcompat
    implementation libs.androidx.core.animation
    implementation libs.androidx.dynamicanimation
    implementation libs.androidx.recyclerview
    implementation libs.androidx.slice.view
    implementation libs.androidx.preference
    implementation libs.androidx.window
    implementation(libs.androidx.ui)

    implementation libs.google.protobuf.javalite
    implementation libs.google.material
    implementation libs.reactivex.rxkotlin3
    implementation libs.elib
    implementation libs.e.telemetry
    implementation libs.timber
    implementation libs.square.logging
    implementation libs.square.okhttp
    implementation libs.kotlinx.serialization.json

    implementation libs.dagger
    ksp libs.dagger.compiler

    implementation project(':animationlib')
    implementation project(':IconLoader')
    implementation project(':msdllib')
    implementation project(':contextualeducationlib')

    implementation fileTree(dir: "libs", include: [
            'Launcher3QuickStepLib.jar',
            'com_android_launcher3_flags_lib.jar',
            'android.os.flags-aconfig-java.jar',
            'com.android.window.flags.window-aconfig-java.jar'
    ])
}

protobuf {
    protoc {
        artifact = "com.google.protobuf:protoc:4.30.0"
    }
    generateProtoTasks {
        all().each { task ->
            task.builtins {
                remove java
                java { option "lite" }
            }
        }
    }
}
